// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/appstore/EnHome.tsx": () => import("../components/mockups/appstore/EnHome.tsx"),
  "./components/mockups/appstore/EnHomePad.tsx": () => import("../components/mockups/appstore/EnHomePad.tsx"),
  "./components/mockups/appstore/EnListing.tsx": () => import("../components/mockups/appstore/EnListing.tsx"),
  "./components/mockups/appstore/EnListingPad.tsx": () => import("../components/mockups/appstore/EnListingPad.tsx"),
  "./components/mockups/appstore/EnSell.tsx": () => import("../components/mockups/appstore/EnSell.tsx"),
  "./components/mockups/appstore/EnSellPad.tsx": () => import("../components/mockups/appstore/EnSellPad.tsx"),
  "./components/mockups/appstore/SvHome.tsx": () => import("../components/mockups/appstore/SvHome.tsx"),
  "./components/mockups/appstore/SvHomePad.tsx": () => import("../components/mockups/appstore/SvHomePad.tsx"),
  "./components/mockups/appstore/SvListing.tsx": () => import("../components/mockups/appstore/SvListing.tsx"),
  "./components/mockups/appstore/SvListingPad.tsx": () => import("../components/mockups/appstore/SvListingPad.tsx"),
  "./components/mockups/appstore/SvSell.tsx": () => import("../components/mockups/appstore/SvSell.tsx"),
  "./components/mockups/appstore/SvSellPad.tsx": () => import("../components/mockups/appstore/SvSellPad.tsx")
};
